### ISSUE TITLE
Hotfix de datos disponibles en la plataforma

### ISSUE THREAD

**Issue by ricalanis** [datoscovidmx/datoscovidmx.github.io#12]

**Comment by ricalanis** [comment]
Lalo, cuando andabamos con la planeación, mencionaste que tenias un tema con los datos por resolver, como quedo? Quedo resuelto?

**Comment by eduhrami** [comment]
Ya se corrigió el bug que dejaba algunos estados sin actualizar con el update de la fuente de datos de SINAVE (ver archivo Javascript)
